// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3TRqYt_yV-GN-UVQuT4cUNOwILtfeI_M',
    appId: '1:587894589031:android:8f910c7afa3ad76007b6c2',
    messagingSenderId: '587894589031',
    projectId: 'ruah-cancionero',
    storageBucket: 'ruah-cancionero.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGD375eQO0-VL2IvIsgcK_klNAyVXWkBQ',
    appId: '1:587894589031:ios:a8ae1c29a129177707b6c2',
    messagingSenderId: '587894589031',
    projectId: 'ruah-cancionero',
    storageBucket: 'ruah-cancionero.appspot.com',
    androidClientId: '587894589031-r83ahamb06gdvb716lrbq202ec18bls9.apps.googleusercontent.com',
    iosClientId: '587894589031-6sfoeum8r4uk2jsd75jsgil25863jkdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.cancioneroruah.RunnerTests',
  );
}
